[tool.poetry]
name = "xlsxtojson"
version = "0.1.0"
description = ""
authors = ["Daniel Romero <danieljromero305@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
openpyxl = "^3.1.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
